---
 - name: Active service apache
   become: yes
   service: 
     name: apache2
     enabled: yes
   notify: start apache

 - name: Configuration l'application et serveur
   include: react.yml
... 
